lore = "Por séculos, o mundo viveu num looping bizarro, totalmente trapped em um ecossistema burocrático que só gerava friction e gap de liquidez, inviabilizando qualquer tese de asset allocation eficiente para a base da pirâmide. O status quo era um verdadeiro deal breaker pro enriquecimento.\n\nMas aí veio o game changer: o turnaround liderado pelas big corps. Demos um full bypass no modelo antigo e escalamos a verdadeira liberdade financeira. Hoje, o mindset mudou: é todo mundo all-in em equity, maximizando o shareholder value. O conceito de deixar capital parado mofando em conta corrente foi totalmente descontinuado. É proibido não performar.\n\n\nMust Earn"

cenarios = {
    1:
        ["BREAKING: TECH MEGAPLAYERS DRIVING THE ALPHA!\n\nAs corporações de grande porte de tecnologia lideram o rali do dia com um growth absurdo, tracionando o valuation do setor pro topo e consolidando o equity de alta capitalização como o verdadeiro safe haven dos asset managers. Simultaneamente, o ecossistema de soluções financeiras roda em modo flat, performando uma consolidação de suporte em um sideways trend previsível e com zero friction. Na contramão, os ativos digitais descentralizados sofrem um healthy profit-taking, abrindo um entry point estratégico para quem busca capturar assimetria em novas bases de preço. É o call perfeito para rebalancear o asset allocation e focar em quem entrega delivery real no intraday!",

        "BREAKING: BIG TECHS CRUSHING EXPECTATIONS!\n\nAs corporações de grande porte entregaram earnings completamente fora da curva neste pregão. O mercado reagiu instantaneamente com uma injeção brutal de liquidez, impulsionando múltiplos e consolidando um novo patamar de valuation para o setor. As plataformas de soluções financeiras seguem operando em modo estável, sem grandes oscilações, enquanto os ativos digitais descentralizados passam por uma realização técnica saudável após semanas de euforia. O fluxo é claro: o capital institucional está estacionando onde existe previsibilidade e delivery.",

        "BREAKING: CORPORATE TITANS ABSORBING ALL THE FLOW!\n\nO capital global acordou extremamente seletivo hoje. As gigantes tecnológicas monopolizam praticamente toda a atenção das mesas, registrando forte expansão de market cap e atraindo gestores em busca de segurança operacional. As fintechs seguem em sideways trend sem grandes catalisadores, enquanto os ativos digitais descentralizados enfrentam um dia de correção após excesso de alavancagem especulativa. O mercado mandou o recado: execution continua valendo mais que narrativa."],

    2:
        ["BREAKING: DISRUPTIVE ASSETS IN VERTICAL RALLY!\n\nMovimento insano no order book global! O mercado de ativos digitais descentralizados entra em bull market vertical, performando um short squeeze violento que joga o pricing dos ativos rumo à lua. Do outro lado, os megaplayers de tecnologia operam em estabilidade total, mantendo um workflow previsível e sem volatilidade nas tabelas de negociação. O sinal de atenção do dia vai para as plataformas de soluções financeiras, que passam por um reajuste técnico de preço e abrem room para a atração de novas teses de venture capital de longo prazo. O capital está trocando de bolso em tempo real: é o flight to risk tracionando o ecossistema!",

        "BREAKING: DIGITAL ASSETS ENTER PARABOLIC MODE!\n\nOs ativos digitais descentralizados simplesmente ignoraram qualquer resistência técnica e entraram em modo foguete. Um fluxo agressivo de novos investidores gerou uma expansão absurda de liquidez e elevou os preços para níveis históricos. Enquanto isso, as gigantes tecnológicas mantêm estabilidade operacional e as plataformas financeiras realizam uma pequena correção para acomodar ganhos recentes. O apetite por risco voltou com força total.",

        "BREAKING: CRYPTO LIQUIDITY EXPLOSION!\n\nO mercado testemunha uma migração massiva de capital para o universo dos ativos digitais descentralizados. Traders e investidores institucionais disputam posição em meio a uma escalada de preços acelerada. As big techs seguem entregando consistência sem grandes oscilações, enquanto o setor financeiro digital sofre uma leve saída de fluxo. Hoje o protagonismo é totalmente descentralizado."],

    3:
        ["BREAKING: THE FINANCIAL INNOVATION TAKE-OVER!\n\nTurnaround histórico no mercado! O shareholder value das plataformas de soluções financeiras dispara de forma ultra-agressiva, surfando uma tese de disrupção que atraiu o capital institucional em peso para o cap table. Enquanto isso, o segmento de ativos digitais descentralizados segue travado e trapped em uma consolidação de preço saudável, sem grandes gatilhos de liquidez imediata. A grande surpresa fica com as gigantes de tecnologia, que realizam um leve recuo para recalibrar múltiplos após uma longa sequência de altas. O hype mudou de endereço: pivotou geral para o ecossistema financeiro digital!",

        "BREAKING: FINTECHS DOMINATING THE MARKET!\n\nAs plataformas de soluções financeiras roubaram completamente a cena. Novos produtos e integrações estratégicas impulsionaram o crescimento do setor, atraindo aportes relevantes dos principais fundos globais. Os ativos digitais seguem em consolidação e as gigantes tecnológicas operam em leve realização após um ciclo prolongado de valorização. O dinheiro está pivotando para quem resolve problemas reais.",

        "BREAKING: DIGITAL FINANCE SUPER CYCLE!\n\nUma onda de inovação tomou conta do mercado financeiro digital. As fintechs aceleram crescimento, expandem receita e conquistam espaço nas carteiras dos investidores institucionais. Enquanto isso, os ativos digitais permanecem lateralizados e as big techs enfrentam um dia de ajuste técnico. O hype agora tem CEP financeiro."],

    4:
        ["BREAKING: INTEGRATED TECH HYPER-GROWTH MOMENTUM!\n\nAlinhamento macro violento nas mesas! As corporações de grande porte e as plataformas de soluções financeiras performam juntas em um momentum bizarramente otimista, escalando a receita, batendo o guidance e deixando os principais benchmarks comendo poeira. É o combo perfeito de scalability e inovação tracionando o mercado global. Mantendo o perfil analítico: a tese de ativos digitais descentralizados sofre um leve bypass hoje, com o fluxo de capital migrando para o topo da pirâmide e gerando uma acomodação natural de preços. Garanta seu equity tradicional porque o rali é institucional!",

        "BREAKING: TECH & FINANCE MEGA PARTNERSHIP RALLY!\n\nO mercado celebra uma forte sinergia entre corporações de tecnologia e plataformas financeiras. O fluxo comprador é consistente nos dois setores, impulsionando indicadores e fortalecendo a tese de crescimento integrado. Os ativos digitais descentralizados ficam em segundo plano hoje, absorvendo uma pequena saída de capital. O smart money está focado em escalabilidade com previsibilidade.",

        "BREAKING: DOUBLE ENGINE GROWTH ACTIVATED!\n\nTecnologia e finanças digitais entram em sintonia perfeita, entregando um dos pregões mais fortes do trimestre. O capital institucional acelera posições nos dois segmentos enquanto o mercado de ativos descentralizados passa por uma pausa estratégica. O momentum está concentrado nas empresas que unem inovação e execução."],

    5:
        ["BREAKING: PURE BARBELL STRATEGY IN ACTION!\n\nO mercado adotou a estratégia perfeita de risk-on: as gigantes de tecnologia escalam forte com fundamentos sólidos e o mercado de ativos digitais descentralizados decola em um rally de alta volatilidade em busca de upside agressivo. É o melhor dos dois mundos para o asset allocation. O contraponto do dia fica por conta das plataformas de soluções financeiras, que enfrentam uma compressão temporária de margem e amargam uma leve busca por suporte no intraday. Esquece o sideways trend, o deal agora é surfar os extremos com grandes corporações e ativos inovadores andando de mãos dadas!",

        "BREAKING: RISK-ON MAXIMUM MODE!\n\nO mercado decidiu ignorar qualquer sinal de cautela. As gigantes tecnológicas renovam máximas enquanto os ativos digitais descentralizados registram ganhos explosivos em um ambiente de apetite extremo por risco. O setor financeiro digital fica para trás temporariamente após uma leve compressão de margens. O dinheiro busca crescimento agressivo.",

        "BREAKING: ALPHA ON BOTH ENDS!\n\nAs corporações de tecnologia entregam resultados sólidos e os ativos digitais capturam o interesse especulativo global. A combinação cria um dos melhores cenários para investidores com perfil growth. Enquanto isso, as fintechs enfrentam um pregão mais desafiador. Hoje o mercado recompensa tanto fundamento quanto volatilidade."],

    6:
        ["BREAKING: HIGH-BETA DISRUPTIVE ALPHA ALERT!\n\nAs corporações tradicionais de grande porte sentiram o peso do fluxo, operando com um recuo estratégico de liquidez e abrindo espaço para um discount atrativo nos múltiplos. Mas o ecossistema macro respira inovação, e o verdadeiro alpha está no growth duplo de plataformas de soluções financeiras e ativos digitais descentralizados! O investidor ativou o modo risk-on total, injetando capital em soluções de vanguarda. Quem apostou contra a disrupção financeira acelerada tomou um margin call inesquecível no dia de hoje. No pain, no gain!",

        "BREAKING: DISRUPTION TAKES CONTROL!\n\nAs grandes corporações enfrentam uma redução temporária de fluxo comprador, mas o capital rapidamente encontra novo destino. Plataformas financeiras e ativos digitais descentralizados lideram os ganhos do dia, impulsionados por investidores em busca de crescimento acelerado. O mercado escolheu inovação acima da tradição.",

        "BREAKING: NEW ECONOMY OUTPERFORMING!\n\nEnquanto empresas tradicionais passam por um período de ajuste, fintechs e ativos digitais concentram a maior parte da liquidez disponível. O movimento reforça a narrativa de transformação financeira e acelera a busca por ativos de alta escalabilidade. Quem apostou no novo está colhendo os resultados."],

    7:
        ["BREAKING: ULTIMATE BULL MARKET RAGE!\n\nCenário dos sonhos para as mesas de operação, sem nenhum downside no horizonte! O alinhamento macro é simplesmente absurdo e simultâneo: corporações de grande porte, plataformas de soluções financeiras e ativos digitais descentralizados engatam um rali histórico de injeção brutal de liquidez institucional. É o mercado inteiro operando em modo god, all-in generalizado, tracionando valuations para máximas nunca antes vistas e maximizando o shareholder value global. Não tem segredo: abre o home broker, surfa a onda e aproveita o green day!",

        "BREAKING: EVERYTHING IS GREEN!\n\nPregão histórico. Tecnologia, finanças digitais e ativos descentralizados sobem simultaneamente em um movimento coordenado raramente observado pelos analistas. A liquidez flui para todos os lados e o sentimento de mercado atinge níveis extremos de otimismo. O ecossistema inteiro está imprimindo performance.",

        "BREAKING: FULL MARKET EUPHORIA!\n\nOs compradores dominaram completamente o mercado. Nenhum setor relevante ficou para trás. Big techs, fintechs e ativos digitais registram fortes valorizações em meio a uma onda de confiança sem precedentes. É um daqueles dias em que qualquer tese parece funcionar."],

    8:
        ["BREAKING: LIQUIDITY CRUNCH & DEEP DISCOUNT OPPORTUNITY!\n\nUma forte busca por liquidez generalizada desaba sobre as mesas de operação neste pregão. Um choque macro congelou temporariamente o ecossistema, desencadeando um downward spiral generalizado e simultâneo. Grandes corporações, plataformas de soluções financeiras e ativos digitais descentralizados estão testando novas bandas de suporte inferior, limpando o excesso de alavancagem do mercado. O risk-off é pesado e o mindset agora é de máxima preservação de caixa: cash is king. Protejam seus assets e fiquem de olho nos gatilhos de entrada porque o mercado está em liquidação!",

        "BREAKING: MACRO FEAR STRIKES AGAIN!\n\nUma forte deterioração do sentimento global derrubou os principais mercados simultaneamente. A liquidez desapareceu das mesas e os investidores migraram para posições defensivas. Grandes corporações, plataformas financeiras e ativos digitais operam sob forte pressão vendedora. O foco agora é sobreviver ao drawdown.",

        "BREAKING: GLOBAL RISK-OFF CASCADE!\n\nO mercado entrou em modo preservação total. Um evento macro inesperado desencadeou vendas generalizadas e provocou uma busca desesperada por caixa. Todos os segmentos sofrem com a redução de liquidez e o aumento da aversão ao risco. O momento exige disciplina e gestão de capital acima de qualquer narrativa."]
}