lore = "Por séculos, o mundo viveu num looping bizarro, totalmente trapped em um ecossistema burocrático que só gerava friction e gap de liquidez, inviabilizando qualquer tese de asset allocation eficiente para a base da pirâmide. O status quo era um verdadeiro deal breaker pro enriquecimento.\n\nMas aí veio o game changer: o turnaround liderado pelas big corps. Demos um full bypass no modelo antigo e escalamos a verdadeira liberdade financeira. Hoje, o mindset mudou: é todo mundo all-in em equity, maximizando o shareholder value. O conceito de deixar capital parado mofando em conta corrente foi totalmente descontinuado. É proibido não performar.\n\n\nMust Earn"
cenarios = {
    1: "BREAKING: TECH MEGAPLAYERS DRIVING THE ALPHA!\n\nAs corporações de grande porte de tecnologia lideram o rali do dia com um growth absurdo, tracionando o valuation do setor pro topo e consolidando o equity de alta capitalização como o verdadeiro safe haven dos asset managers. Simultaneamente, o ecossistema de soluções financeiras roda em modo flat, performando uma consolidação de suporte em um sideways trend previsível e com zero friction. Na contramão, os ativos digitais descentralizados sofrem um healthy profit-taking, abrindo um entry point estratégico para quem busca capturar assimetria em novas bases de preço. É o call perfeito para rebalancear o asset allocation e focar em quem entrega delivery real no intraday!",

    2: "BREAKING: DISRUPTIVE ASSETS IN VERTICAL RALLY!\n\nMovimento insano no order book global! O mercado de ativos digitais descentralizados entra em bull market vertical, performando um short squeeze violento que joga o pricing dos ativos rumo à lua. Do outro lado, os megaplayers de tecnologia operam em estabilidade total, mantendo um workflow previsível e sem volatilidade nas tabelas de negociação. O sinal de atenção do dia vai para as plataformas de soluções financeiras, que passam por um reajuste técnico de preço e abrem room para a atração de novas teses de venture capital de longo prazo. O capital está trocando de bolso em tempo real: é o flight to risk tracionando o ecossistema!",

    3: "BREAKING: THE FINANCIAL INNOVATION TAKE-OVER!\n\nTurnaround histórico no mercado! O shareholder value das plataformas de soluções financeiras dispara de forma ultra-agressiva, surfando uma tese de disrupção que atraiu o capital institucional em peso para o cap table. Enquanto isso, o segmento de ativos digitais descentralizados segue travado e trapped em uma consolidação de preço saudável, sem grandes gatilhos de liquidez imediata. A grande surpresa fica com as gigantes de tecnologia, que realizam um leve recuo para recalibrar múltiplos após uma longa sequência de altas. O hype mudou de endereço: pivotou geral para o ecossistema financeiro digital!",

    4: "BREAKING: INTEGRATED TECH HYPER-GROWTH MOMENTUM!\n\nAlinhamento macro violento nas mesas! As corporações de grande porte e as plataformas de soluções financeiras performam juntas em um momentum bizarramente otimista, escalando a receita, batendo o guidance e deixando os principais benchmarks comendo poeira. É o combo perfeito de scalability e inovação tracionando o mercado global. Mantendo o perfil analítico: a tese de ativos digitais descentralizados sofre um leve bypass hoje, com o fluxo de capital migrando para o topo da pirâmide e gerando uma acomodação natural de preços. Garanta seu equity tradicional porque o rali é institucional!",

    5: "BREAKING: PURE BARBELL STRATEGY IN ACTION!\n\nO mercado adotou a estratégia perfeita de risk-on: as gigantes de tecnologia escalam forte com fundamentos sólidos e o mercado de ativos digitais descentralizados decola em um rally de alta volatilidade em busca de upside agressivo. É o melhor dos dois mundos para o asset allocation. O contraponto do dia fica por conta das plataformas de soluções financeiras, que enfrentam uma compressão temporária de margem e amargam uma leve busca por suporte no intraday. Esquece o sideways trend, o deal agora é surfar os extremos com grandes corporações e ativos inovadores andando de mãos dadas!",

    6: "BREAKING: HIGH-BETA DISRUPTIVE ALPHA ALERT!\n\nAs corporações tradicionais de grande porte sentiram o peso do fluxo, operando com um recuo estratégico de liquidez e abrindo espaço para um discount atrativo nos múltiplos. Mas o ecossistema macro respira inovação, e o verdadeiro alpha está no growth duplo de plataformas de soluções financeiras e ativos digitais descentralizados! O investidor ativou o modo risk-on total, injetando capital em soluções de vanguarda. Quem apostou contra a disrupção financeira acelerada tomou um margin call inesquecível no dia de hoje. No pain, no gain!",

    7: "BREAKING: ULTIMATE BULL MARKET RAGE!\n\nCenário dos sonhos para as mesas de operação, sem nenhum downside no horizonte! O alinhamento macro é simplesmente absurdo e simultâneo: corporações de grande porte, plataformas de soluções financeiras e ativos digitais descentralizados engatam um rali histórico de injeção brutal de liquidez institucional. É o mercado inteiro operando em modo god, all-in generalizado, tracionando valuations para máximas nunca antes vistas e maximizando o shareholder value global. Não tem segredo: abre o home broker, surfa a onda e aproveita o green day!",

    8: "BREAKING: LIQUIDITY CRUNCH & DEEP DISCOUNT OPPORTUNITY!\n\nUma forte busca por liquidez generalizada desaba sobre as mesas de operação neste pregão. Um choque macro congelou temporariamente o ecossistema, desencadeando um downward spiral generalizado e simultâneo. Grandes corporações, plataformas de soluções financeiras e ativos digitais descentralizados estão testando novas bandas de suporte inferior, limpando o excesso de alavancagem do mercado. O risk-off é pesado e o mindset agora é de máxima preservação de caixa: cash is king. Protejam seus assets e fiquem de olho nos gatilhos de entrada porque o mercado está em liquidação!"
}